spring:
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时
      key-prefix: 'spring_cache:'

system:
  # 验证码类型 math 数字计算 char 字符验证
  captcha-type: math

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: id
      logic-not-delete-value: 0

logging:
  level:
    com.nbb.template.system.mapper: debug
